project:
  type: website
  output-dir: doc

website:
  title: "Forschungsorientiertes Praktikum I – Grundlagen der Forschung"
  navbar:
    search: true
    left:
      - text: Sessions
        file: sessions/sessions_overview.qmd  
      - text: Topics
        file: topics/topics_overview.qmd
      - about.qmd
    right:
      - icon: github
        href: https://github.com/nicebread/Empra1
        aria-label: GitHub

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: source

execute:
  freeze: auto
