---
title: "Forschungsorientierte Praktikum I – Grundlagen der Forschung"
subtitle: "BSc Psychologie, LMU"
---


# Sessions Overview

| #   | Date       | Topic                                                                                           | Notes                                                | Homework                                                                                       |
| --- | ---------- | ----------------------------------------------------------------------------------------------- | ---------------------------------------------------- | ---------------------------------------------------------------------------------------------- |
| 1   | 2024-04-19 | [S1 - Formalitäten, Open Science, p-hack](sessions/S1-Introduction.qmd)                         |                                                      | create OSF account; practice p-hacking                                                         |
| 2   | 2024-04-26 | [S2 - Einführung Intimitätsmotiv](sessions/S2-Intimacy.qmd) - with Nensy                        |                                                      | Develop interventions                                                                          |
| 3   | 2024-05-03 | [S3 - Motive 2; Kausalität](sessions/S3-Motives_Causality.qmd)                                  |                                                      | Read Ch. 1 of Experimentology                                                                  |
| 4   | 2024-05-10 | [S4 - Studie planen; Literaturrecherche](sessions/S4-DesignPlanning-LitSearch.qmd) - with Nensy | Fragebögen überarbeiten; Ziel: Hypothesen aufstellen | HA: Vp-Akquise in Gruppen planen (Material, Kanäle, etc.); Literaturrecherche in Gruppe machen |
| 5   | 2024-05-17 | Poweranalyse                                                                                    |                                                      | Read Preregistration Challenge                                                                 |
| 6   | 2024-05-24 | Prereg intro                                                                                    |                                                      |                                                                                                |
| 7   | 2024-05-31 | **Brückentag - ggf. online / Nensy Vertretung**: Studie finalisieren                            |                                                      | Studie testen                                                                                  |
| 8   | 2024-06-07 | Letzter Feinschliff Studie; Prereg gemeinsam finalisieren                                       |                                                      | Open data lesen; Studienstart ganz fertig machen                                               |
| 9   | 2024-06-14 | Open Data & Anonymisierung                                                                      | Studienstart!                                        | Codebuch erstellen                                                                             |
| 10  | 2024-06-21 | good coding practices; Quarto 1                                                                 |                                                      | VP-Akquise; Quarto / Rmarkdown self-paced tutorial                                             |
| 11  | 2024-06-28 | papaja                                                                                          |                                                      |                                                                                                |
| 12  | 2024-07-05 | Datenanalyse 1                                                                                  | Studienende                                          |                                                                                                |
| 13  | 2024-07-12 |                                                                                                 |                                                      |                                                                                                |
| 14  | 2024-07-19 | How-to Hausarbeit                                                                               |                                                      |                                                                                                |

<!-- 

| #   | Date       | Topic                                                                                       | Homework                                                                                  |
| --- | ---------- | ------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------- |
| 1   | 2024-04-19 | [S1 - Formalitäten, Open Science, p-hack](sessions/S1-Introduction.qmd)                     | Intimitätsmotiv Einführung lesen; create OSF account                                      |
| 2   | 2024-04-26 | [S2 - Einführung Intimitätsmotiv; Kausalität] - with Nensy                                  | Read [Ch. 1 of Experimentology](https://experimentology.io/1-experiments); p-hacking üben |
| 3   | 2024-05-03 | [S3 - Literaturrecherche]                                                                   | Studiendesign überlegen; Literaturrecherche                                               |
| 4   | 2024-05-10 | **Brückentag - ggf. online** [S4 - Studie planen] - with Nensy                              | Fragebögen überarbeiten; [HA - Read Preregistration Challenge]                            |
| 5   | 2024-05-17 | [S5 -Studie finalisieren; Prereg]                                                           | Studienmaterial erstellen, VP-Akquise planen; Prereg weiter ausfüllen                     |
| 6   | 2024-05-24 | [S6 - Studie finalisieren]                                                                  | App testen; Open data lesen; Studienstart ganz fertig machen; Zeiten in Tellmi testen     |
| 7   | 2024-05-31 | **Brückentag - ggf. online / Nensy Vertretung** [S7 - Studie final finalisieren, Open Data] | VP-Akquise; Quarto / Rmarkdown self-paced tutorial                                        |
| 8   | 2024-06-07 |                                                                                             | VP-Akquise; Quarto / Rmarkdown self-paced tutorial                                        |
| 9   | 2024-06-14 | [S8 - good coding practices; Quarto 1]                                                      | Vpnakquise; das erste Papaja-Dokument erstellen                                           |
| 10  | 2024-06-21 | [S9 - papaja, open data]                                                                    | Codebuch erstellen                                                                        |
| 11  | 2024-06-28 | [S10 - Poweranalyse; finales Datenanalysemodell]                                            | Anonymisierungsumfrage ausfüllen; Paper zu privacy-fails lesen                            |
| 12  | 2024-07-05 | [S11 - Prereg fertig machen, Anonymisierung]                                                |                                                                                           |
| 13  | 2024-07-12 |                                                                                             |                                                                                           |
| 14  | 2024-07-19 | [S12 - Finale Datenanalyse, Hausarbeit]                                                     |                                                                                           |
 -->
